name: release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4 
      - uses: federicocarboni/setup-ffmpeg@v3.1

      - name: Install cargo-bundle
        run: cargo install cargo-packager --locked

      - name: Build
        run: cargo build --release
  
      - name: Bundle release
        run: cargo packager --release
