name: release

on:
  release:
    types: [created]

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            archive: zip
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3 
      - uses: federicocarboni/setup-ffmpeg@v3.1

      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
